### PR TITLE
Mount read only shared data volume

### LINKED ISSUE #35: Mount extra volumes
#34 added support for mounting user's home directories.

There should also be the possibility to mount extra volumes, for example and read-only directory with shared data for all users.

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #35.

Mount the `/srv/data` volume in the user containers.

- [x] Update the documentation to mention this volume
- [x] Update the overview diagram

### CODE REVIEW

**Comment by pierrepo** [comment]
Could it be the `/data` directory instead of `/src/data`?

**Comment by jtpio** [comment]
Why not `/srv/data` as recommended in http://tljh.jupyter.org/en/latest/howto/content/share-data.html#option-2-create-a-read-only-shared-folder-for-data?

**Comment by pierrepo** [comment]
OK. Let's go with `/srv/data`

**Comment by jtpio** [comment]
Good!

**Pull request merged**
