### PR TITLE
Add cockpit playbook and service

### LINKED ISSUE #70: Add a simple monitoring tool
Depending on the tool, it could be installed using the Ansible playbooks, or as a dependency to the TLJH plugin.

For now we could consider two simple ones. By simple it means they just need to be installed with almost zero configuration.

- [Cockpit](https://cockpit-project.org/), as suggested by @pierrepo 
- [Glances](https://nicolargo.github.io/glances), which might be a bit more minimal but can be installed with pip.

Another thing to consider is whether they should be accessible via the JupyterHub UI. And in that case restrict access to admin users only.

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #70 

Add a `cockpit.yml` playbook to install cockpit on the host.

Add `cockpit` as a JupyterHub service so it:

- shows up in the JupyterHub interface
- can be proxied through JupyterHub Traefik's proxy and keep the SSL termination on Traefik

cockpit

### TODO

- [x] ~Whitelist some users~
- [x] Show services to admin users only?
- [x] Add / update the documentation
- [x] Update overview diagram to include cockpit behind Traefik

### CODE REVIEW

**Comment by jtpio** [comment]
Showing services to Admin users only in the nav bar.

Not admin:

image

Admin:

image

**Comment by jtpio** [comment]
cc @pierrepo if you want to have a look :point_up: 

Also do you think it's necessary to have a whitelist of users that can access the cockpit dashboard?

The documentation says:

> When a user is logged into Cockpit, they are logged into a normal session that has exactly the same privileges as if they logged in via SSH or on the console.

https://cockpit-project.org/guide/latest/privileges

**Comment by jtpio** [comment]
This is what a user without admin privileges sees on cockpit:

image

**Comment by jtpio** [comment]
Also since cockpit offers a web based terminal interface (similar to running a terminal from the Jupyter interface), this could be a nice way for normal users to access the server without having to enable SSH login with password:

image

**Comment by pierrepo** [comment]
> this could be a nice way for normal users to access the server

As for now, let's allow access to cockpit only for admin users.

**Comment by jtpio** [comment]
Unfortunately there doesn't seem to be an easy way to whitelist users in cockpit after searching the docs (or it is quite hidden). 

But like they say in the docs the user has the same privileges as if they logged in via SSH anyway.

Also the link is made visible to JupyterHub admin users only now, which makes Cockpit less discoverable: 

image

**Comment by jtpio** [comment]
This is what a "normal" user sees when they try to access the Docker Containers section for example:

image

Even if this user is a JupyterHub admin, they will need to be added to the `docker` / `sudo` group to be able to access this information (mentioned in the PlasmaBio docs).

**Comment by jtpio** [comment]
Let's merge this so it's easier to test and get an idea of what it looks like.

We can always open a new issue to discuss access to Cockpit.

**Pull request merged**
