### PR TITLE
Add a JupyterHub service to manage user images

### LINKED ISSUE #23: Add new environments (docker images) to the deployment
There should be a clear process (and documentation) on how to add new environments to the hub installation.

These environments will come from repositories containing the materials, and be built using `repo2docker`:

Example: https://github.com/plasmabio/materials-example

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #23. 

Add a service managed by JupyterHub to handle user images via a UI.

image

add-image

- [x] Add the service
- [x] retrieve images that are being built
- [x] add a form to add a new repo
- [x] populate the list of built images in the spawner
- [x] Update the documentation to show how to find the UI
- [x] Update the overview diagram to show how the service interacts with the rest of the stack
- [x] Add a section in the docs to explain how images are built under the hood

### CODE REVIEW

**Comment by jtpio** [comment]
This is what the UI could look like:

image

As a first step, we should be able to start with something simple that doesn't involve a database or a shared file / state to keep track of the images.

Instead we could look up the existing images directly using the docker client.

We also need a way to manage the builds that are in progress, maybe by looking at the running repo2docker build containers.

cc @pierrepo if you have any feedback on this

**Comment by jtpio** [comment]
Current status:

image

We can drop the "Build" button. Instead one can remove the images and add them again.

Still need to:

- retrieve images that are being built
- add a form to add a new repo
- remove images (can be done in a separate PR)
- populate the list of built images in the spawner

**Comment by pierrepo** [comment]
Hi @jtpio :wave: 
This looks very promising. I did not have in mind that the image under construction might be an issue. But you are right to underline we have to deal with it since a user might want to re-create an image under construction if he does not see it in the interface...

**Comment by pierrepo** [comment]
One more thought, if a user want to *refresh* an existing image. He first updates his repo but then, does he need to delete the actual image and register a new one? Would a *refresh* button be useful here?

**Comment by jtpio** [comment]
It depends on how we think about the Docker images.

Docker images are immutable, so it might not be clear what a refresh button should do. If the `ref` is `master`, then we could say that it would grab the latest master and rebuild the image. But if the `ref` is a commit hash, then refreshing wouldn't update anything.

Otherwise if we want to promote pinning on specific commits (so it's easier to investigate issues and they correspond to a specific point in time), that would indeed mean adding a new image with a new commit hash, and removing the old one after.

For now we could probably try the add / remove workflow and see afterwards if some of this should be made more intuitive in terms of UX.

**Pull request merged**
